# Build and deploy Training API

trigger:
- master

resources:
- repo: self

variables:
  tag: 'v4'

stages:
- stage: Build
  jobs:  
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Registry'
        repository: 'oitgaden/trainingapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy Training API: $(tag)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'Training API Cluster'
        namespace: 'default'
        manifests: 'kubernetes/deployment.yaml'
