# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'v4'

stages:
- stage: Build
  jobs:  
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'Docker Hub Registry'
        repository: 'oitgaden/trainingapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
    - task: KubernetesManifest@0
      displayName: 'Deploy Training API: $(tag)'
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'Training API Cluster'
        namespace: 'default'
        manifests: 'kubernetes/deployment.yaml'